SeedProvider and related stuff
contariaa/atum pull request #8
Opened 2024-09-10 02:17 UTC by DuncanRuns

SeedQueue compat is not tested at all yet, wanted to get the code up anyway

2024-09-11 15:46 UTC, KingContaria requested changes
My main concern is what happens when the reset key is pressed during the waiting screen since `Atum#shouldReset` is set to false before opening the `AtumCreateWorldScreen`. Maybe atum providing the waitingscreen was right, then you could just check that in `Atum#scheduleReset`
I'm also not a big fan of IllegalStateExceptions without reasons, they should give some description of what went wrong, for null checks `Objects.requireNonNull` is fine

2024-09-11 15:46 UTC, KingContaria commented on src/main/java/me/voidxwalker/autoreset/mixin/config/MoreOptionsDialogMixin.java
> +        this.seedText = seed == null ? "" : seed;
`seed` can't be null since we get it from an `Optional`

2024-09-11 15:46 UTC, KingContaria commented on src/main/java/me/voidxwalker/autoreset/mixin/MinecraftClientMixin.java
> +    }
The seed string will be `null` when Atum isn't running

2024-09-11 15:46 UTC, KingContaria commented on src/main/java/me/voidxwalker/autoreset/mixin/config/CreateWorldScreenMixin.java
> +
I think this code can just be moved into `modifyAtumCreateWorldScreen` so we don't need two extra fields, you can make an extra method in `IMoreOptionsDialog` for setting the seed string

2024-09-11 17:47 UTC, DuncanRuns commented
- AtumWaitingScreen is an abstract Screen class, seed providers will still need to provide an implementation of a waiting screen, but AtumWaitingScreen allows an instanceof check for the hotkey and also allows providing some useful methods that will likely be used
- Code moved to modifyAtumCreateWorldScreen
  - Defensive null check code removed in this refactor as well
- LevelLoadingScreen for non atum loading fixed
- Added `String exceptionMessage` parameter to ensureState, replaced some usages with requireNonNull

2024-09-11 21:00 UTC, KingContaria requested changes
`Atum#isSetSeed` should probably return false when a custom seedprovider is registered, its used in chunkcacher so kind of critical
Probably also best to add the AtumWaitingScreen check to `Atum#isBlocking` just in case, prevents it from creating a new world during the waiting screen and instead immediately resets after
Atum should probably ensure it has either stopped running or that a new AtumCreateWorldScreen has been opened when the AtumWaitingScreen is closed, you can probably override `Screen#removed` for that

2024-09-11 21:00 UTC, contariaa commented on src/main/java/me/voidxwalker/autoreset/mixin/config/CreateWorldScreenMixin.java
> +                    }
I'd rather only wait for the seed once and print a warning/throw an exception if it fails

2024-09-12 02:26 UTC, DuncanRuns commented on src/main/java/me/voidxwalker/autoreset/mixin/config/CreateWorldScreenMixin.java
> +                    }
My original reasoning for this was that if SeedQueue ever changed to be able to open multiple AtumCreateWorldScreens, then two waitForSeeds could race and only one would get it and the other should continue to wait.
But if we guarantee that screens can only open one at a time then yeah waiting once would be fine.

2024-09-12 02:38 UTC, DuncanRuns commented
> Atum should probably ensure it has either stopped running or that a new AtumCreateWorldScreen has been opened when the AtumWaitingScreen is closed, you can probably override `Screen#removed` for that

currentScreen.removed() is called as the first step in openScreen(), so I cannot check from removed() if an AtumCreateWorldScreen is being opened.

2024-09-12 10:23 UTC, KingContaria commented
I think it's fine to just set a flag that a new AtumCreateWorldScreen is created in `AtumWaitingScreen#onSeedFound`, you could even use that to ensure it's only ever called once with a lovely ensureState

2024-09-12 10:54 UTC, DuncanRuns commented
Ah good idea

2024-09-12 17:53 UTC, DuncanRuns commented
Some things to consider:
- Moving AtumCreateWorldScreen to gui package, or moving AtumWaitingScreen out of gui package
- Moving SeedProvider to interfaces package, unless that package is meant for duck interfaces only
- Formatting? I noticed some mixins don't use multiple lines for the annotation parameters like in SQ so I guess at some point you'd go through everything for formatting anyway.

2024-09-12 19:17 UTC, DuncanRuns commented
As said in original comment, SeedQueue compatibility wasn't tested and still isn't, this is something I will need to get around to before setting as Ready to review for allowing merging.

2024-09-12 20:01 UTC, DuncanRuns commented
hmmmm
![image](https://github.com/user-attachments/assets/f227c820-de5f-454c-a665-b26b8aeb4d01)

2024-09-12 20:09 UTC, DuncanRuns commented
oh I see
this.seedText in CreateWorldScreen is not what is used for setting the seed in actual world gen, seedTextField.getText() is used.
seetTextField.setText(this.seedText) is called from init, which allows changing this.seedText to work if ran before init, such as in constructor. This broke when moving seed provider logic from constructor to init.

2024-09-13 15:50 UTC, KingContaria commented
> Some things to consider:
> 
> * Moving AtumCreateWorldScreen to gui package, or moving AtumWaitingScreen out of gui package
> 
> * Moving SeedProvider to interfaces package, unless that package is meant for duck interfaces only
> 

I have actually thought about this, I think its best to just move AtumWaitingScreen and SeedProvider into an api package, maybe even with a seedprovider subpackage incase other stuff is ever added

> * Formatting? I noticed the mixins that I saw don't use multiple lines for the annotation parameters like in SQ so I guess at some point you'd go through everything for formatting if you wanted to anyway.

Yea I figured it would be easier if i just did formatting stuff later, doing it through reviews is kind of tedious

2024-09-13 15:53 UTC, KingContaria commented
Oh also you could ensure state in `AtumWaitingScreen#cancelWorldCreation` and `continueWorldCreation` so only one of them is ever called and they are only ever called once

2024-09-13 17:28 UTC, DuncanRuns commented
Something that's missing is some way to cancel seed waiting for SeedQueue (with `waitForSeed()`)
Right now it can just finish waitForSeed and then return an empty optional to force an ISE, but that feels mmmmmmmmm cringe

2024-09-13 18:40 UTC, contariaa commented
You could just return a dummy seed, would probably be easier for me than implementing a way to cancel world creation in seedqueue

2024-09-22 19:32 UTC, KingContaria approved these changes
Lgtm :)

2024-09-22 19:32 UTC, merged